trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  backendImageName: 'clientes-backend'
  frontendImageName: 'clientes-frontend'

stages:
  - stage: Build
    jobs:
      - job: BuildBackend
        steps:
          - checkout: self
          - task: Docker@2
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(backendImageName)'
              command: 'buildAndPush'
              Dockerfile: 'backend/Dockerfile'
              tags: 'latest'
      - job: BuildFrontend
        steps:
          - checkout: self
          - task: Docker@2
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(frontendImageName)'
              command: 'buildAndPush'
              Dockerfile: 'frontend/Dockerfile'
              tags: 'latest'
  - stage: Deploy
    jobs:
      - job: DeployToAzure
        steps:
          - script: echo "Deploy para Azure aqui"
